### ISSUE TITLE
The train_g.sh and train_g2l.sh files give the wrong arguments. 

### ISSUE THREAD

**Issue by Coco970963014** [vkola-lab/ajpa2021#2]
I was recently reproducing this paper and found that the parameters given in the train_g.sh and train_g2l.sh files are wrong, size_p should match the size of the cropped patches, otherwise it will report an error in the _crop_global() function because the dimension is wrong.
The error is reported similar to the following.
`  File "/root/autodl-tmp/ajpa2021-master/models/resnet_fpn.py", line 338, in _crop_global
    crop = torch.stack(crop, dim=0) # stack into mini-batch
RuntimeError: stack expects each tensor to be equal size, but got [256, 3, 8] at entry 0 and [256, 3, 7] at entry 1
`
or
`  File "/root/autodl-tmp/ajpa2021-master/models/resnet_fpn.py", line 195, in forward
    p5 = self.toplayer(torch.cat([c5] + [F.interpolate(c5_ext[0], size=c5.size()[2:], **self._up_kwargs)], dim=1))
  File "/root/miniconda3/envs/ajpa/lib/python3.8/site-packages/torch/nn/functional.py", line 3151, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: input and output sizes should be greater than 0, but got input (H: 1, W: 0) output (H: 16, W: 16)
`
I changed the size_p in the train_g.sh and train_g2l.sh files to 224 and the error reporting disappeared.

**Comment by GSWS** [comment]
You need to ensure that all tensors being stacked are of the same size. This could involve padding, cropping, or resizing tensors to a common size before stacking. Ensure that the tensors have valid dimensions before interpolation when checking the patch cropping in the local branch.
